services:
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: dev_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "8084:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin
